#!/bin/bash

# This bash script automates the tests

wget https://github.com/stephengaito/pdf2htmlEX/releases/download/continuous/appImageName

export APPIMAGE_NAME=$(cat appImageName)

wget https://github.com/stephengaito/pdf2htmlEX/releases/download/continuous/$APPIMAGE_NAME

chmod a+x $APPIMAGE_NAME

if ! ./$APPIMAGE_NAME --version ; then
  echo "COULD NOT run the AppImage"
  exit 1
fi

if [ -x "$(which docker)" ]; then

  wget https://github.com/stephengaito/pdf2htmlEX/releases/download/continuous/dockerImageName

  export DOCKER_IMAGE_NAME=$(cat dockerImageName)

  if ! docker run $DOCKER_IMAGE_NAME --version ; then
    echo "COULD NOT run the Docker Image"
    exit 1
  fi

fi



