#!/bin/bash

# This bash script copies the various scripts in the .travisScripts to the 
# /home/travis/bin directory to ensure the current scripts are not lost 
# when we checkout different versions of pdf2htmlEX

cp .travisScripts/* $HOME/bin

cp dobuild   $HOME/bin
cp doinstall $HOME/bin

