#!/bin/bash

# This bash script automates the creation of an AppImage for pdf2htmlEX
# It is based upon code taken from
#   https://github.com/AppImage/pkg2appimage
# and
#   https://github.com/AppImage/AppImages

mkdir -p buildAppImage

cd buildAppImage

wget -q https://github.com/AppImage/AppImages/raw/master/functions.sh \
  -O ./functions.sh

. ./functions.sh

apt download -y apt libapt-pkg5.0 libbz2-1.0 liblzma5 \
   multiarch-support zlib1g dpkg

mkdir -p pdf2htmlEX.AppImage

