#!/bin/bash

# This bash script builds pdf2htmlEX using Clang (if it is installed)

cd pdf2htmlEX
mkdir build
cd build
CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
make $MAKE_PARALLEL
