#!/bin/bash

# This bash script build FontForge

source buildScripts/versionEnvs


# This is a work-around to fix TravisCI's declaration of PYTHON_CFLAGS
# which is then honoured exactly as is by the fontforge bootstrap and
# configure steps
#
if [ -n "$PYTHON_CFLAGS" ] ; then
  export PYTHON_CFLAGS="$(pkg-config --cflags python) $PYTHON_CFLAGS"
fi

echo ""
echo "-------------------------------"
pkg-config --cflags python
pkg-config --cflags python-2.7
echo $PYTHON_CFLAGS
echo $PYTHON_LIBS
echo "-------------------------------"
echo ""

cd fontforge
./bootstrap
./configure --disable-silent-rules

echo ""
echo "-------------------------------"
cat config.log
echo "-------------------------------"
echo ""

echo ""
echo "-------------------------------"
cat fontforge/Makefile
echo "-------------------------------"
echo ""


# Apply any patches required for fontforge raw sources before we make
#
for APATCHFILE in $(ls ../patches/fontforge-$FONTFORGE_VERSION-*)
do
  echo "patching fontforge using [$APATCHFILE]" 
  patch -p 1 < $APATCHFILE
done

tree /usr/include/python2.7

#cd fontforge
#make -n
#cd ..

make

#make $MAKE_PARALLEL

