#!/bin/bash

# This bash script builds the latest poppler

echo ""
echo "-------------------------------------------------------------------"
echo "BUILDING Poppler"
echo "-------------------------------------------------------------------"
echo ""

cd poppler
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX \
    -DENABLE_LIBOPENJPEG=none ..
make $MAKE_PARALLEL
