#!/bin/bash

set -ev

# This bash script builds pdf2htmlEX

echo ""
echo "-------------------------------------------------------------------"
echo "BUILDING pdf2htmlEX (using gcc)"
echo "-------------------------------------------------------------------"
echo ""

cd pdf2htmlEX
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX ..
make $MAKE_PARALLEL
