#!/bin/bash

set -ev

# This bash script creates the pdf2htmlEX AppImage and Docker Images

#################
# do the creation

./buildScripts/reportEnvs

./buildScripts/createAppImage

./buildScripts/createDebianPackage

./buildScripts/createDockerImageInside

if [ -x "$(which docker)" ]; then
  ./buildScripts/createDockerImageOutside
fi



