#!/bin/bash 

# This bash script creates a docker image from an existing pdf2htmlEX
#
# This is the part which can run *inside* a docker container.

echo ""
echo "-------------------------------------------------------------------"
echo "CREATING pdf2htmlEX Docker Image (run inside a docker container)"
echo "-------------------------------------------------------------------"
echo ""

# Collect everything that will be needed...

source buildScripts/reSourceVersionEnvs

source buildScripts/dockerFunctions

set -ev

mkdir -p imageBuild/dockerDir

cd pdf2htmlEX/build

sudo rm -rf install_manifest.txt

make install DESTDIR=../../imageBuild/dockerDir

cd ../../poppler-data

make install                                  \
  prefix=$PDF2HTMLEX_PREFIX                   \
  datadir=$PDF2HTMLEX_PREFIX/share/pdf2htmlEX \
  DESTDIR=../imageBuild/dockerDir

cd ../imageBuild/dockerDir

copy_deps

# Make sure directories can be traversed by nobody
#
#find . -type d -exec chmod 755 {} \;
#
# Make sure files can be read by nobody
#
#find . -type f -exec chmod 644 {} \;
