#!/bin/bash 

# This bash script creates an AppImage for pdf2htmlEX

source ./buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "CREATING pdf2htmlEX AppImage"
echo "-------------------------------------------------------------------"
echo ""

# For appimage output plugin
#
export VERSION="$PDF2HTMLEX_BRANCH-$BUILD_TIME"
export APPIMAGE_NAME="pdf2htmlEX-$PDF2HTMLEX_BRANCH-$BUILD_TIME-$MACHINE_ARCH.AppImage"

echo "export APPIMAGE_NAME=\"$APPIMAGE_NAME\"" >> buildScripts/reSourceVersionEnvs

mkdir -p imageBuild/appDir/usr/lib/

cd pdf2htmlEX/build

sudo rm -rf install_manifest.txt

make install DESTDIR=../../imageBuild/appDir

cd ../../poppler-data

make install prefix=$PDF2HTMLEX_PREFIX DESTDIR=../imageBuild/appDir

cd ../imageBuild

# force libfontconfig into AppImage (linuxdeploy blacklists libfontconfig)
#
cp /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 appDir/usr/lib/

LINUX_DEPLOY_APP_IMAGE=linuxdeploy-$MACHINE_ARCH.AppImage

wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/$LINUX_DEPLOY_APP_IMAGE

chmod a+x $LINUX_DEPLOY_APP_IMAGE

./$LINUX_DEPLOY_APP_IMAGE			\
  -e appDir/$PDF2HTMLEX_PREFIX/bin/pdf2htmlEX	\
  --create-desktop-file				\
  -i ../pdf2htmlEX/logo/pdf2htmlEX.svg		\
  --appdir=appDir				\
  --output appimage


