#!/bin/bash 

# This bash script creates a docker image from an existing pdf2htmlEX

echo ""
echo "-------------------------------------------------------------------"
echo "CREATING pdf2htmlEX Docker Image"
echo "-------------------------------------------------------------------"
echo ""

if [ -x "$(which docker)" ]; then

  source buildScripts/reSourceVersionEnvs

  source buildScripts/dockerFunctions

  mkdir -p imageBuild/dockerDir

  cd pdf2htmlEX/build

  sudo rm -rf install_manifest.txt

  make install DESTDIR=../../imageBuild/dockerDir

  cd ../../imageBuild/dockerDir

  copy_deps

  delete_blacklisted

  cat > Dockerfile <<DOCKERFILE_HERE_DOC
FROM $DOCKER_FROM
COPY ./ /
RUN ldconfig
ENTRYPOINT ["/usr/local/bin/pdf2htmlEX"]
DOCKERFILE_HERE_DOC

  cd ..

  docker build -t $DOCKER_NAME dockerDir

else
  echo "Docker is not installed... skipping creation of a docker image."
fi

