#!/bin/sh

set -ev

# This shell script creates the pdf2htmlEX AppImage and Container Images

#################
# do the creation

./buildScripts/reportEnvs

./buildScripts/createAppImage

./buildScripts/createDebianPackage

if [ -x "$(which docker)" -o -x "$(which podman)" ]; then
  ./buildScripts/createContainerUbuntuImageFromDeb
fi
