#!/bin/bash

# This bash script builds the complete pdf2htmlEX application LOCALLY
# (It does not create the AppImage or Docker images)

# Adjust the following two environment variables to suit your needs
#
export UNATTENDED="--assume-yes"
export MAKE_PARALLEL="-j $(nproc)"

./buildScripts/reportEnvs        || { echo 'reportEnvs FAILED'        ; exit 1 ; }

./buildScripts/getBuildTools     || { echo 'getBuildTools FAILED'     ; exit 1 ; }

./buildScripts/getDevLibraries   || { echo 'getDevLibraries FAILED'   ; exit 1 ; }

./buildScripts/getPoppler        || { echo 'getPoppler FAILED'        ; exit 1 ; }

./buildScripts/buildPoppler      || { echo 'buildPoppler FAILED'      ; exit 1 ; }

./buildScripts/installPoppler    || { echo 'installPoppler FAILED'    ; exit 1 ; }

./buildScripts/getFontforge      || { echo 'getFontforge FAILED'      ; exit 1 ; }

./buildScripts/buildFontforge    || { echo 'buildFontforge FAILED'    ; exit 1 ; }

./buildScripts/installFontforge  || { echo 'installFontforge FAILED'  ; exit 1 ; }

./buildScripts/buildPdf2htmlEX   || { echo 'buildPdf2htmlEX FAILED'   ; exit 1 ; }

./buildScripts/installPdf2htmlEX || { echo 'installPdf2htmlEX FAILED' ; exit 1 ; }

./buildScripts/createAppImage    || { echo 'createAppImage FAILED'    ; exit 1 ; }

./buildScripts/createDockerImage || { echo 'createDockerImage FAILED' ; exit 1 ; }

./buildScripts/uploadRelease     || { echo 'uploadRelease FAILED'     ; exit 1 ; }
