#!/bin/bash

# This bash script builds the complete pdf2htmlEX application LOCALLY
# (It does not create the AppImage or Docker images)

export UNATTENDED=--assume-yes

./buildScripts/getBuildTools

./buildScripts/getDevLibraries

./buildScripts/getPoppler

./buildScripts/buildPoppler

./buildScripts/installPoppler

./buildScripts/getFontForge

./buildScripts/buildFontForge

./buildScripts/installFontForge

./buildScripts/buildPdf2htmlEX

./buildScripts/installPdf2htmlEX
