#!/bin/bash

# This bash script automates getting the required build tools (apt install)

sudo apt install	\
  aptitude		\
  git			\
  pkg-config		\
  ruby			\
  cmake			\
  make			\
  gcc			\
  g++			\
  tree     

