#!/bin/bash

# This bash script automates getting the required build tools (brew install)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING Build Tools (using Home/Linux Brew)"
echo "-------------------------------------------------------------------"
echo ""

set -ev

brew update
brew install \
  autoconf   \
  libtool    \
  make       \
  gettext    \
  openjdk    \
  jq         \
  tree

# Removed the following for homeBrew (macos on travis)
#  git        \
#  pkg-config \
#  cmake      \
#  ruby       \
#  gcc        \
