#!/bin/bash

# This bash script automates getting the development libraries required to 
# build poppler and fontforge

# set the bash environment variable 'UNATTENDED' to '--assume-yes' for
# unattended use (for example in the .travis.yml script)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING development libraries (using APT)"
echo "  (UNATTENDED: [$UNATTENDED])"
echo "-------------------------------------------------------------------"
echo ""

sudo apt-get update
sudo apt-get $UNATTENDED install	\
  libcairo-dev				\
  libspiro-dev				\
  libpng-dev				\
  libjpeg-dev				\
  poppler-data				\
  libpango1.0-dev			\
  liblcms2-dev				\
  libxml2-dev				\
  libuninameslist-dev			\
  python3-dev
