#!/bin/bash

set -ev

# This bash script automates getting the development libraries required to 
# build poppler and fontforge (using Home/Linux Brew)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING development libraries (using Home/Linux Brew)"
echo "-------------------------------------------------------------------"
echo ""

brew update
brew install \
  cairo      \
  libpng     \
  jpeg       \
  libxml2    \

#  libspiro		\
#  pango			\
#  little-cms2		\
#  libuninameslist	\
