#!/bin/bash

# This bash script gets and unpacks the latest fontforge AppImage

source buildScripts/versionEnvs

FONTFORGE_SRC=fontforge-$FONTFORGE_VERSION.tar.gz

rm -rf $FONTFORGE_SRC
rm -rf fontforge

wget https://github.com/fontforge/fontforge/releases/download/$FONTFORGE_VERSION/$FONTFORGE_SRC

tar xvf $FONTFORGE_SRC

mv fontforge-$FONTFORGE_VERSION fontforge
