#!/bin/bash

# This bash script automates the process of getting the original pdf2htmlEX 
# source

PDF2HTMLEX_VERSION=newBuildSystem

wget https://codeload.github.com/stephengaito/pdf2htmlEX/zip/$PDF2HTMLEX_VERSION

mv $PDF2HTMLEX_VERSION $PDF2HTMLEX_VERSION.zip

sudo apt install unzip

unzip $PDF2HTMLEX_VERSION.zip

mv pdf2htmlEX-$PDF2HTMLEX_VERSION pdf2htmlEX
