#!/bin/bash

set -ev

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING FontForge locally"
echo "  (UNATTENDED: [$UNATTENDED])"
echo "-------------------------------------------------------------------"
echo ""


if [ -z "$UNATTENDED" ] ; then
  echo "WARNING: this may over-write any existing"
  echo "FontForge version you have installed on your system."
  echo "This may break other packages/applications."
  echo ""
  echo "This installation assumes you have 'sudo' privileges."
  echo ""
  echo "Type ctrl-c now if DO NOT want to continue"
  read -p "Type anything else to continue: "
fi

cd fontforge
sudo make install
sudo ldconfig;
