#!/bin/bash

# This bash script installs Poppler into the local system

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING Poppler locally"
echo "  (UNATTENDED: [$UNATTENDED])"
echo "-------------------------------------------------------------------"
echo ""


if [ -z "$UNATTENDED" ] ; then
  echo "WARNING: this may over-write any existing"
  echo "Poppler version you have installed on your system."
  echo "This may break other packages/applications."
  echo ""
  echo "This installation assumes you have 'sudo' privileges."
  echo ""
  echo "Type ctrl-c now if DO NOT want to continue"
  read -p "Type anything else to continue: "
fi

set -ev

cd poppler/build
sudo make install

cd ..

sudo mkdir -p               $PDF2HTMLEX_PREFIX/include/poppler
sudo cp poppler/*.h $PDF2HTMLEX_PREFIX/include/poppler

sudo mkdir -p               $PDF2HTMLEX_PREFIX/include/poppler/goo
sudo cp goo/*.h     $PDF2HTMLEX_PREFIX/include/poppler/goo

sudo mkdir -p               $PDF2HTMLEX_PREFIX/include/poppler/fofi
sudo cp fofi/*.h    $PDF2HTMLEX_PREFIX/include/poppler/fofi

sudo mkdir -p               $PDF2HTMLEX_PREFIX/include/poppler/splash
sudo cp splash/*.h  $PDF2HTMLEX_PREFIX/include/poppler/splash

sudo cp build/poppler/poppler-config.h \
        $PDF2HTMLEX_PREFIX/include/poppler

cd ../poppler-data

sudo make install prefix=$PDF2HTMLEX_PREFIX

