#!/bin/bash

if [ -z "$UNATTENDED" ] ; then

  echo "This installation assumes you have 'sudo' privileges"
  echo ""
  echo "Type ctrl-c now if DO NOT want to continue"
  read -p "Type anything else to continue: "

fi

cd pdf2htmlEX/build

sudo make install
