#!/bin/sh

# This shell script reports the more important TRAVIS environment variables

# source ./buildScripts/reSourceVersionEnvs
. ./buildScripts/reSourceVersionEnvs

echo ""
echo "TravisCI env:"
echo "             dist: [$TRAVIS_DIST]"
echo "              tag: [$TRAVIS_TAG]"
echo "           branch: [$TRAVIS_BRANCH]"
echo "           commit: [$TRAVIS_COMMIT]"
echo "        build dir: [$TRAVIS_BUILD_DIR]"
echo "        repo slug: [$TRAVIS_REPO_SLUG]"
echo ""

echo "Build env:"
echo "           prefix: [$PDF2HTMLEX_PREFIX]"
echo "       unattended: [$UNATTENDED]"
echo "    make parallel: [$MAKE_PARALLEL]"
echo "               OS: [$BUILD_OS]"
echo "     distribution: [$BUILD_DIST]"
echo "  linuxdeploy url: [$LINUX_DEPLOY_URL]"
echo ""

echo "pdf2htmlEX env:"
echo "          version: [$PDF2HTMLEX_VERSION]"
echo "          poppler: [$POPPLER_VERSION]"
echo "        fontforge: [$FONTFORGE_VERSION]"
echo "       pdf2htmlEX: [$PDF2HTMLEX_BRANCH]"
echo "     machine arch: [$MACHINE_ARCH]"
echo ""

echo "release env:"
echo "       build date: [$BUILD_DATE]"
echo "       build time: [$BUILD_TIME]"
echo "   container from: [$CONTAINER_FROM]"
echo "   container name: [$CONTAINER_NAME]"
echo "    appImage name: [$APPIMAGE_NAME]"
echo "        dpkg name: [$DPKG_NAME]"
echo "uploadTool suffix: [$UPLOADTOOL_SUFFIX]"
echo ""
