#!/bin/bash

set -ev

# This bash script runs the pdf2htmlEX tests

cd pdf2htmlEX/test

# The following is only needed for the local browser tests
#
./installAutomaticTestSoftware

./runLocalTests

./runLocalBrowserTests

