#!/bin/bash

# This bash script builds everyting on an TravisCI Mac OSx worker

# See:
# https://docs.travis-ci.com/user/installing-dependencies/#using-homebrew-without-addon-on-older-macos-images
# For details on obtaining/using the correct ruby version for homebrew.

sudo apt-get update
sudo apt-get install gcc-5 # many of the linuxBrew bottles are compiled with gcc-5

brew tap pdf2htmlEX/homebrew-brewTap
brew update
brew install pdf2htmlex-new -s --cc=gcc-5
