#!/bin/bash

# This bash script builds everyting on an TravisCI Mac OSx worker

rvm use 2.6 --install --binary
brew tap pdf2htmlEX/homebrew-brewTap
brew update
brew install pdf2htmlex-new
rvm use $TRAVIS_RUBY_VERSION # optionally, switch back to the Ruby version you need.
