#!/bin/sh

# This shell script uploads already existing pdf2htmlEX AppImage and Container
# Images

################
# do the uploads

set -ev

./buildScripts/reportEnvs           || { echo 'reportEnvs FAILED'           ; exit 1 ; }

./buildScripts/uploadGitHubRelease  || { echo 'uploadGitHubRelease FAILED'  ; exit 1 ; }

./buildScripts/uploadContainerImage || { echo 'uploadContainerImage FAILED' ; exit 1 ; }


