#!/bin/bash

# This bash script exports environment variables for the latest software
# versions

#export POPPLER_VERSION=poppler-0.82.0
export POPPLER_VERSION=poppler-0.81.0

#export FONTFORGE_VERSION=20190801
export FONTFORGE_VERSION=20170731

if [ -z "$PDF2HTMLEX_BRANCH" ]; then
  export PDF2HTMLEX_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
fi

export MACHINE_ARCH="$(uname -m)"

export BUILD_TIME="$(date +%Y_%m_%d-%H_%M_%S)"

export DOCKER_FROM=ubuntu:18.04

export DOCKER_NAME="$DOCKER_USERNAME/pdf2htmlex:$PDF2HTMLEX_BRANCH-$BUILD_TIME"

export APPIMAGE_NAME="pdf2htmlEX-$PDF2HTMLEX_BRANCH-$BUILD_TIME-$MACHINE_ARCH.AppImage"

echo "export POPPLER_VERSION=\"$POPPLER_VERSION\""     >  buildScripts/reSourceVersionEnvs
echo "export FONTFORGE_VERSION=\"$FONTFORGE_VERSION\"" >> buildScripts/reSourceVersionEnvs
echo "export PDF2HTMLEX_BRANCH=\"$PDF2HTMLEX_BRANCH\"" >> buildScripts/reSourceVersionEnvs
echo "export MACHINE_ARCH=\"$MACHINE_ARCH\""           >> buildScripts/reSourceVersionEnvs
echo "export BUILD_TIME=\"$BUILD_TIME\""               >> buildScripts/reSourceVersionEnvs
echo "export DOCKER_FROM=\"$DOCKER_FROM\""             >> buildScripts/reSourceVersionEnvs
echo "export DOCKER_NAME=\"$DOCKER_NAME\""             >> buildScripts/reSourceVersionEnvs
echo "export APPIMAGE_NAME=\"$APPIMAGE_NAME\""         >> buildScripts/reSourceVersionEnvs

