#!/bin/bash

# This bash script exports environment variables for the latest software
# versions

#export POPPLER_VERSION=poppler-0.82.0
export POPPLER_VERSION=poppler-0.81.0

#export FONTFORGE_VERSION=20190801
export FONTFORGE_VERSION=20170731

if [ -z "$PDF2HTMLEX_BRANCH" ]; then
  export PDF2HTMLEX_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
fi

export MACHINE_ARCH="$(uname -m)"

export BUILD_TIME="$(date +%Y_%m_%d-%H_%M_%S)"

export DOCKER_FROM=ubuntu:18.04

export DOCKER_NAME="$DOCKER_USERNAME/pdf2htmlex:$PDF2HTMLEX_BRANCH-$BUILD_TIME"

export APPIMAGE_NAME="pdf2htmlEX-$PDF2HTMLEX_BRANCH-$BUILD_TIME-$MACHINE_ARCH.AppImage"

echo > buildScripts/reSourceVersionEnvs <<RESOURCE_VERSION_ENVS
export POPPLER_VERSION="$POPPERL_VERSION"
export FONTFORGE_VERSION="$FONTFORGE_VERSION"
export PDF2HTMLEX_BRANCH="$PDF2HTMLEX_BRANCH"
export MACHINE_ARCH="$MACHINE_ARCH"
export BUILD_TIME="$BUILD_TIME"
export DOCKER_FROM="$DOCKER_FROM"
export DOCKER_NAME="$DOCKER_NAME"
export APPIMAGE_NAME="$APPIMAGE_NAME"
RESOURCE_VERSION_ENVS
